#include "prefix/prefix.h"

#include "data-mov/mov.h"
#include "data-mov/xchg.h"

#include "arith/dec.h"
#include "arith/inc.h"
#include "arith/neg.h"
#include "arith/imul.h"
#include "arith/mul.h"
#include "arith/idiv.h"
#include "arith/div.h"

#include "logic/and.h"
#include "logic/or.h"
#include "logic/not.h"
#include "logic/xor.h"
#include "logic/sar.h"
#include "logic/shl.h"
#include "logic/shr.h"
#include "logic/shrd.h"

#include "string/rep.h"

#include "misc/misc.h"

#include "special/special.h"

#include "new-add/push.h"
#include "new-add/call.h"
#include "new-add/test.h"
#include "new-add/je.h"
#include "new-add/pop.h"
#include "new-add/ret.h"
#include "new-add/add.h"
#include "new-add/cmp.h"
#include "new-add/sub.h"
#include "new-add/sbb.h"
#include "new-add/jmp.h"
#include "new-add/jbe.h"
#include "new-add/jle.h"
#include "new-add/jl.h"
#include "new-add/ja.h"
#include "new-add/jg.h"
#include "new-add/js.h"
#include "new-add/jns.h"
#include "new-add/jge.h"
#include "new-add/clt.h"
#include "new-add/jne.h"
#include "new-add/leave.h"
#include "new-add/lea.h"
#include "new-add/adc.h"
#include "new-add/movzb.h"
#include "new-add/movzw.h"
#include "new-add/cmovs.h"
#include "new-add/movsb.h"
#include "new-add/movsw.h"
#include "new-add/movs.h"
#include "new-add/setne.h"
#include "new-add/nop.h"
#include "new-add/lods.h"
#include "new-add/scas.h"
#include "new-add/stos.h"
#include "new-add/lgdt.h"
#include "new-add/std.h"
#include "new-add/cld.h"

